// examples/svelte-product-gallery/src/App.svelte
<script>
  import {onMount} from 'svelte'

  onMount(() => {
		const gallery = document.getElementById('gallery');

    if (window && gallery) {
      window.cloudinary
        .galleryWidget({
          container: gallery,
          cloudName: import.meta.env.VITE_CLOUDINARY_CLOUD_NAME,
          aspectRatio: "16:9",
          mediaAssets: [
            {
              tag: "gallery",
              transformation: { crop: "fill" },
            },
          ],
        })
        .render();
    }
		
	});
</script>

<main class="main">
      <div class="container">
        <h1 class="title">Svelte &amp; Cloudinary Product Gallery</h1>
      </div>

      <div class="container">
        <div id="gallery" />
      </div>

      <div class="container">
        <h2>Resources</h2>
        <p>
          <a href="https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/svelte-product-gallery">
            See the code on github.com.
          </a>
        </p>
      </div>
</main>

<style>
  .container {
  width: 100%;
  max-width: 1024px;
  padding: 0 1em;
  margin: 3em auto;
}

.title {
  text-align: center;
  margin: 2em 0;
}
</style>

// examples/solid-product-gallery/src/App.jsx
import { onMount } from "solid-js";

import "./App.css";

function App() {
  let galleryRef;
  
  onMount(() => {
    if (window && galleryRef) {
      window.cloudinary
        .galleryWidget({
          container: galleryRef,
          cloudName: import.meta.env.VITE_CLOUDINARY_CLOUD_NAME,
          aspectRatio: "16:9",
          mediaAssets: [
            {
              tag: "solid-product-gallery",
              transformation: { crop: "fill" },
            },
          ],
        })
        .render();
    }
  });

  return (
    <>
      <main className="main">
        <div className="container">
          <h1 className="title">Solid &amp; Cloudinary Product Gallery</h1>
        </div>

        <div className="container">
          <div ref={galleryRef}></div>
        </div>

        <div className="container">
          <h2>Resources</h2>
          <p>
            <a href="https://github.com/colbyfayock/cloudinary-examples/tree/main/examples/solid-product-gallery">
              See the code on github.com.
            </a>
          </p>
        </div>
      </main>
    </>
  );
}

export default App;
