// examples/react-ts-media-library/src/App.tsx
import { useState } from 'react';
import MediaLibrary from './components/MediaLibrary';
import type { MediaLibraryInsertResults } from './components/MediaLibrary/MediaLibrary.types';

import './App.css'

function App() {
  const [assets, setAssets] = useState<MediaLibraryInsertResults['assets']|undefined>();

  function handleOnInsert({ assets }: MediaLibraryInsertResults) {
    if ( Array.isArray(assets) ) {
      setAssets(assets);
    }
  }

  return (
    <main className="main">
      <div className="container">
        <h1 className="title">
          React &amp; Cloudinary Media Library
        </h1>
      </div>

      <div className="container">
        <div className="card">
          <MediaLibrary onInsert={handleOnInsert} options={{
            insertCaption: 'Add Assets',
            multiple: true
          }}>
            {({ open }) => {
              function handleOnOpen() {
                if ( typeof open == 'function' ) {
                  open();
                }
              }
              return (
                <button onClick={handleOnOpen}>
                  Open Library
                </button>
              );
            }}
          </MediaLibrary>
        </div>
      </div>

      <div className="container">
        {assets?.map(asset => {
          return (
            <div key={asset.public_id} className="card">
              { asset.resource_type === 'image' && (
                <img width={asset.width} height={asset.height} src={asset.secure_url} alt="" />
              )}

              { asset.resource_type === 'video' && (
                <video width={asset.width} height={asset.height} src={asset.secure_url} controls />
              )}
            </div>
          )
        })}
      </div>

      <div className="container">
        <h2>Resources</h2>
        <p>
          <a href="https://github.com/colbyfayock/cloudinary-examples/tree/main/examples/react-upload-widget-preset">See the code on github.com.</a>
        </p>
      </div>
    </main>
  )
}

export default App

// examples/vue-upload-widget-preset/src/App.vue
<script setup>
import { ref } from "vue";
import UploadWidget from "./components/UploadWidget.vue";

const url = ref("");
const errorMessage = ref(false);

function onUpload({ error, result }) {
  url.value = result?.info.secure_url;
  errorMessage.value = error ? error : false;
}
</script>

<template>
  <main class="main">
    <div class="container">
      <h1 class="title">Vue.js &amp; Cloudinary Upload Widget</h1>
    </div>

    <div class="container">
      <h2>Unsigned with Upload Preset</h2>

      <UploadWidget @on-upload="onUpload" />

      <p v-if="error">{{ error.message }}</p>

      <p v-if="url">
        <img :src="url" alt="Uploaded resource" />
      </p>
      <p v-if="url">{{ url }}</p>
    </div>

    <div class="container">
      <h2>Resources</h2>
      <p>
        <a
          href="https://github.com/colbyfayock/cloudinary-examples/tree/main/examples/vue-upload-widget-preset"
          >See the code on github.com.</a
        >
      </p>
    </div>
  </main>
</template>

<style scoped>
.container {
  width: 100%;
  max-width: 1024px;
  padding: 0 1em;
  margin: 0 auto;
}

.title {
  text-align: center;
  margin: 2em 0;
}

.subtitle {
  font-weight: normal;
  text-align: center;
  margin: -1em 0 2em;
}
</style>
